exports.farms = [
  {
    farmId: 0,
    name: 'Osmosis OSMO Staking',
    platform: 'Osmosis',
    chain: 'Osmosis',
    stakingTokenSymbol: 'arOSMO',
    rewardTokenSymbols: ['arOSMO'],
  },
  {
    farmId: 1,
    name: 'Osmosis ATOM/OSMO liquidity mining',
    platform: 'Osmosis',
    chain: 'Osmosis',
    stakingTokenSymbol: 'arOsmosisATOMOSMO',
    rewardTokenSymbols: ['arOSMO'],
  },
  {
    farmId: 2,
    name: 'Pancakeswap CAKE/BNB liquidity mining',
    platform: 'Pancakeswap',
    chain: 'BSC',
    stakingTokenSymbol: 'arPancakeswapCAKEBNB',
    rewardTokenSymbols: ['arCAKE'],
  },
  {
    farmId: 3,
    name: 'Pancakeswap BUSD/BNB liquidity mining',
    platform: 'Pancakeswap',
    chain: 'BSC',
    stakingTokenSymbol: 'arPancakeswapBUSDBNB',
    rewardTokenSymbols: ['arCAKE'],
  },
  {
    farmId: 4,
    name: 'Quickswap ETH/USDC liquidity mining',
    platform: 'Quickswap',
    chain: 'Polygon',
    stakingTokenSymbol: 'arQuickswapETHUSDC',
    rewardTokenSymbols: ['arQUICK'],
  },
  {
    farmId: 5,
    name: 'Quickswap ETH/QUICK liquidity mining',
    platform: 'Quickswap',
    chain: 'Polygon',
    stakingTokenSymbol: 'arQuickswapETHQUICK',
    rewardTokenSymbols: ['arQUICK'],
  },
  {
    farmId: 6,
    name: 'Raydium RAY/SOL liquidity mining',
    platform: 'Raydium',
    chain: 'Solana',
    stakingTokenSymbol: 'arRaydiumRAYSOL',
    rewardTokenSymbols: ['arRAY'],
  },
  {
    farmId: 7,
    name: 'Raydium RAY/USDT liquidity mining',
    platform: 'Raydium',
    chain: 'Solana',
    stakingTokenSymbol: 'arRaydiumRAYUSDT',
    rewardTokenSymbols: ['arRAY'],
  },
  {
    farmId: 8,
    name: 'Uniswap ETH/USDT liquidity mining',
    platform: 'Uniswap',
    chain: 'Ethereum',
    stakingTokenSymbol: 'arUniswapETHUSDT',
    rewardTokenSymbols: [],
  },
  {
    farmId: 9,
    name: 'Curve DAI/USDC/USDT liquidity mining',
    platform: 'Curve',
    chain: 'Ethereum',
    stakingTokenSymbol: 'arCurveDAIUSDCUSDT',
    rewardTokenSymbols: ['arCRV'],
  },
  {
    farmId: 10,
    name: 'Sushiswap ETH/TRU liquidity mining',
    platform: 'Sushiswap',
    chain: 'Ethereum',
    stakingTokenSymbol: 'arSushiswapETHTRU',
    rewardTokenSymbols: ['arSUSHI', 'arTRU'],
  },
  {
    farmId: 11,
    name: 'Aave USDT lending',
    platform: 'Aave',
    chain: 'Ethereum',
    stakingTokenSymbol: 'arUSD',
    rewardTokenSymbols: ['arUSD'],
  },
];
